### ISSUE TITLE
Build 392: Bugs in new clearcampexporbs feature

### ISSUE THREAD

**Issue by LlmDl** [mung3r/ecoCreature#142]
Using:

CraftBukkit version git-Bukkit-1.7.2-R0.3-b3020jnks (MC: 1.7.2)

ecoCreature 0.2.2-SNAPSHOT-b392 

When I updated I used a brand-new config and re-configured by hand.

Relevant config sections:

```
  Hunting:
    AllowCamping: false
    ClearCampDrops: false
    ClearCampExpOrbs: false
    CampingByEntity: true
    CampingByDistance: false
    CampRadius: 40
    ClearDefaultDrops: false
    OverrideDrops: false


  Towny:
    InTown:
      Amount: 0.2
      ClearExpOrbs: true
```

Bug 1: Though ClearCampDrops was false I was not receiving any regualr drops from monster spawners' monsters. I would receive the odd enchanted bow/piece of armour, but no bones from any skeleton. This occurred in towns and outside of towns.

Bug 2: There is a hard-coded NoCampMessage 'You find no rewards camping monster spawners.' when you are killing mobs from spawners. Messages.Spawner: false in my config and editing the message in the config had no effect.

Bug 3: Outside of town, no xp orbs or mob drops came from monsters spawned via spawner-cubes, though I think I have it configured to do so.
