### ISSUE TITLE
Individual OverrideDrop for each mob.

### ISSUE THREAD

**Issue by erik1988** [mung3r/ecoCreature#151]
Would it be possible to only override/clear drops of certain mobs?
I would like to be able to add "OverrideDrops: true/false" under each mob so that I get more controll. The reason is that I would like to limit the amount of meat droped by animals, however i dont want to clear the armor/swords that the zombies picks up.

    # Replace instead of stack rewards drops/items
    # Default: true
    OverrideDrops: true
RewardTable:
  Cow:
    Drops:
    - 'leather:1:55'
    - 'raw beef:1:50'
    OverrideDrops: true
  Zombie:
    Drops:
    - 'gold nugget:1-2:60'
    OverrideDrops: false

**Comment by mung3r** [comment]
Yup, this is supported. Here's an example:
```
RewardTable:
  Cow:
    Drops:
    Drops:
    - 'leather:2:100'
    - 'raw beef:1-3:100'
    Hunting:
      OverrideDrops: true
````
In fact, you can override anything in the global 'Hunting' section on a per mob basis.
