### ISSUE TITLE
mob drops

### ISSUE THREAD

**Issue by rbos** [mung3r/ecoCreature#16]
Mob drops are entirely disabled moving to 0.9b from 0.8b on CB1597.  Killed several dozen pigs, no pork.

I've stripped out all item drops from mobs and changed it to additive mode in the config file, ie:

```
    # Replace instead of stack rewards drops/items
    # Default: true
    OverrideDrops: false

Skeleton:
    Coin_Minimum: 0.5
    Coin_Maximum: 1.00
    Coin_Percent: 50.0
```

Otherwise it is a stock install.

Edit: Also adjusted coin values and percentages a bit.
