### ISSUE TITLE
PenalizeDeath Not charging

### ISSUE THREAD

**Issue by kripts** [mung3r/ecoCreature#20]
Hi, I cant seem to get the pernalizedeath working here is my config:

```
    PenalizeDeath: true
    PenalizeType: true
    PenalizeAmount: 15.0
```

This means that 15% will be taken off correct?
I have set up the permissions and still cant seem to get it on 
I was also wondering how to set a percentage gain when you kill a player instead of a set amount

```
Player:
    Coin_Minimum: 20.00
    Coin_Maximum: 20.00
    Coin_Percent: 50.0
    NoReward_Message: ''
    Reward_Message: '&7You are awarded &6<amt>&7 for murdering &5<crt>&7.'
    Penalty_Message: '&7You are penalized &6<amt>&7 for murdering &5<crt>&7.'
```

Im using the latest Bukkit and Pex, 
Thanks :)
