### ISSUE TITLE
Multiple mob rewards

### ISSUE THREAD

**Issue by darkdemon42** [mung3r/ecoCreature#36]
Hi, I'm getting multiple money rewards for killing mobs, and multiple messages. Drops are fine and work okay, but money rewards multiply by up to 4.

In this picture I killed 1 skeleton, 1 pig, and 1 spider.

I was rewarded a total of 12 coin for it.

http://i40.tinypic.com/idsv49.png

From my default.yml:
(it is in additive mode with a chance of dropping gold nuggets, which works, it's just the money that doesn't)

```
Skeleton:
    Drops: '371:1:40'
    Coin_Minimum: 1.00
    Coin_Maximum: 3.00
    Coin_Percent: 100.0

Spider:
    Drops: '371:1:40'
    Coin_Minimum: 0.50
    Coin_Maximum: 1.50
    Coin_Percent: 50.0
```
