### ISSUE TITLE
Drop listing for config

### ISSUE THREAD

**Issue by mung3r** [mung3r/ecoCreature#50]
Submitted by Bob2351723:

Instead of this:

```
Squid:
    Drops: '351:2:75;349:2:40;350:1:5;19:1:25'
    Coin_Minimum: 0.10
    Coin_Maximum: 1.50
    Coin_Percent: 1.0
```

Can I use this:

```
Squid:
    Drops: 
      - 351:2:75
      - 349:2:40
      - 350:1:5
      - 19:1:25
    Coin_Minimum: 0.10
    Coin_Maximum: 1.50
    Coin_Percent: 1.0
```

Thanks in advance, double thanks if you say yes...

Bob
